/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#ee9800",
        "tertiary-fixed-dim": "#4cd7f6",
        "outline-variant": "#5c3f40",
        "on-surface": "#e3e2e7",
        "on-primary": "#68001a",
        "background": "#121317",
        "tertiary": "#4cd7f6",
        "on-tertiary": "#003640",
        "secondary": "#ffb95f",
        "on-primary-fixed": "#40000c",
        "primary-fixed-dim": "#ffb3b6",
        "secondary-fixed": "#ffddb8",
        "surface-container": "#1f1f24",
        "on-tertiary-fixed": "#001f26",
        "surface-container-low": "#1a1b20",
        "on-surface-variant": "#e5bdbe",
        "on-secondary": "#472a00",
        "surface-bright": "#38393d",
        "tertiary-container": "#007f95",
        "primary-container": "#e11d48",
        "primary-fixed": "#ffdada",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "primary": "#ffb3b6",
        "on-secondary-container": "#5b3800",
        "on-error-container": "#ffdad6",
        "surface-variant": "#343439",
        "surface-container-highest": "#343439",
        "on-secondary-fixed-variant": "#653e00",
        "surface-container-lowest": "#0d0e12",
        "outline": "#ac8889",
        "on-secondary-fixed": "#2a1700",
        "inverse-primary": "#be0037",
        "inverse-surface": "#e3e2e7",
        "tertiary-fixed": "#acedff",
        "surface-dim": "#121317",
        "on-primary-container": "#fffaf9",
        "on-tertiary-container": "#f5fcff",
        "inverse-on-surface": "#2f3035",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface": "#121317",
        "surface-tint": "#ffb3b6",
        "on-primary-fixed-variant": "#920028",
        "surface-container-high": "#292a2e",
        "secondary-fixed-dim": "#ffb95f",
        "on-background": "#e3e2e7"
      },
      fontFamily: {
        headline: ["'Space Grotesk'", "sans-serif"],
        body: ["'Inter'", "sans-serif"]
      }
    },
  },
  plugins: [],
}
